### ISSUE TITLE
use BNode with surf

### ISSUE THREAD

**Issue by zhiboz** [cosminbasca/surfrdf#13]
here is the code snippet from the `federation.py` example

```
Movie = session.get_class(surf.ns.SURF['Movie'], store = 'local')
m1 = Movie('http://baseuri/m1')
m1.surf_title = "Movie 1"
```

trying to create a blank node with rdf.BNode but couldn't figure out how. any pointer would be appreciated!

**Comment by cosminbasca** [comment]
the *BNode* in *surf* is the *BNode* from *rdflib*, here is a simple example of how to use it (from rdflib docs):

```python
>>> from rdflib import BNode
>>> anode = BNode()
>>> anode
rdflib.term.BNode('AFwALAKU0')
>>> anode.n3()
u'_:AFwALAKU0'
```

**Comment by zhiboz** [comment]
thanks for your quick response!

i guess i knew it is also possible to do 

`from surf.rdf import BNode`

what i couldn't figure out is how to use a bnode in `surf` way, like

```
from surf.rdf import BNode
anode = BNode()

anode.foaf_name = 'Joe'
```

**Comment by cosminbasca** [comment]
you can only use *surf* resources that way, any *rdflib* terms function via their own apis, a surf resource can be created from the *session* like this: 

```
Person = surf.ns.FOAF["Person"]
john_uri = "http://example/john"
instance = session.get_resource(john_uri, Person)
```

instead of giving your resource a *URI* you can try to pass a blank node:

```
Person = surf.ns.FOAF["Person"]
john_uri = BNode()
instance = session.get_resource(john_uri, Person)
```
I have not tested this though so not sure if this works, although it should. Let me know

**Comment by zhiboz** [comment]
well, made some progress with the above code suggested, but when trying to serialize it, here is what it produces

```
<http://base.uri/patent619351> a ns1:Patent ;
    ns1:SPC <Nb1664098ce124da3b0e46a3bcf3310d4> .

<Nb1664098ce124da3b0e46a3bcf3310d4> a ns1:SPC ;
    ns1:country "Sweden" ;
```

but we'd expect a blank node in `[ ]` in serialization

```
<http://base.uri/patent619351> a ns1:Patent ;
    ns1:SPC [ ... ] .
```

**Comment by cosminbasca** [comment]
surf delegates the serialization to the underlying *rdflib* graph, perhaps there is a bug in the rdflib serializer? It's been a while since I looked at RDF serialization formats. One way to debug this is to get the graph from the resource or the session and to try to serialize it yourself and see where the problem possibly occurs. Look for a *.graph* property. HTH, Cosmin
